app = "band-archive-api"
primary_region = "nrt"

[build]

[env]
  FLASK_CONFIG = "config.ProductionConfig"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "data"
  destination = "/data"
